### ISSUE TITLE
Niedziałający algorytm sortowania kubełkowego

### ISSUE THREAD

**Issue by Tymisko** [wernexnrs/MATURA-INFORMATYKA#9]
Dla tablicy
tab = [1, 5, 1, 5, 1, 2, 4, 5]
```python
Traceback (most recent call last):
  File "...\algorithms.py", line 207, in <module>
    print(bucketSort(table))
  File "...\algorithms.py", line 187, in bucketSort
    buckets[int(len(arr) * arr[i])].append(arr[i])
IndexError: list index out of range
```

**Comment by wernexnrs** [comment]
Naprawione. Dziękuje za informację.
